// Rebuilds lib/src/web/codec_worker_js.g.dart: compiles the web codec
// worker (lib/src/web/codec_worker_main.dart) with dart2js and embeds the
// JavaScript, so apps get it without serving an extra file. Also records
// which of this package's sources went into it, and a hash of them, so
// test/codec_worker_test.dart can tell when it needs rebuilding. Run from
// the package root after changing any of those sources:
//
//     dart run tool/build_codec_worker.dart
import 'dart:convert';
import 'dart:io';

import '../test/helpers/source_hash.dart';

void main() {
  final out = Directory.systemTemp.createTempSync('svs_codec_worker_');
  try {
    final js = '${out.path}/codec_worker.js';
    final result = Process.runSync(Platform.resolvedExecutable, [
      'compile',
      'js',
      '-O4',
      '--no-source-maps',
      'lib/src/web/codec_worker_main.dart',
      '-o',
      js,
    ]);
    if (result.exitCode != 0) {
      stderr
        ..write(result.stdout)
        ..write(result.stderr);
      exit(1);
    }
    final root = Directory.current.uri;
    final sources = [
      for (final line in File('$js.deps').readAsLinesSync())
        if (line.startsWith(root.resolve('lib/').toString()))
          Uri.parse(line).path.substring(root.path.length),
    ]..sort();
    final source = File(js).readAsStringSync();
    final literal = jsonEncode(source).replaceAll(r'$', r'\$');
    File('lib/src/web/codec_worker_js.g.dart').writeAsStringSync('''
// Generated by tool/build_codec_worker.dart — do not edit by hand.
// ignore_for_file: lines_longer_than_80_chars

/// The web codec worker, compiled by dart2js.
const codecWorkerJs = $literal;

/// This package's sources [codecWorkerJs] was compiled from, relative to
/// the package root, and a hash of their contents.
const codecWorkerSources = <String>[
${[for (final s in sources) "  '$s',"].join('\n')}
];
const codecWorkerSourceHash = '${sourceHash(sources)}';
''');
    Process.runSync(Platform.resolvedExecutable, [
      'format',
      'lib/src/web/codec_worker_js.g.dart',
    ]);
    stdout.writeln(
      'Wrote ${source.length} characters of JavaScript from '
      '${sources.length} sources.',
    );
  } finally {
    out.deleteSync(recursive: true);
  }
}
