// Regenerates test/jpeg2000/j2k_fixtures.g.dart from the codestreams in
// test/fixtures/jpeg2000 (see generate.sh there): each fixture's bytes, and
// a fingerprint of what this package's decoder makes of it at full and
// reduced resolution. Tests on the web can't read files, so they decode the
// embedded bytes and compare against these fingerprints; the VM tests check
// the same decodes against OpenJPEG. Run from the package root:
//
//     dart run tool/generate_jpeg2000_fixtures.dart
import 'dart:convert';
import 'dart:io';

import 'package:svs/src/codec/jpeg2000/j2k_decoder.dart';

import '../test/jpeg2000/j2k_fingerprint.dart';

void main() {
  final files =
      Directory('test/fixtures/jpeg2000')
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.j2k'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  final out = StringBuffer()
    ..writeln('// Generated by tool/generate_jpeg2000_fixtures.dart — do not')
    ..writeln('// edit by hand.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// Each fixture codestream, base64-encoded.')
    ..writeln('const j2kFixtures = <String, String>{');
  final prints = StringBuffer();
  for (final file in files) {
    final name = file.uri.pathSegments.last.replaceAll('.j2k', '');
    final bytes = file.readAsBytesSync();
    out.writeln("  '$name': '${base64Encode(bytes)}',");
    for (var reduce = 0; reduce <= 2; reduce++) {
      try {
        final image = decodeJ2k(bytes, reducedResolutionFactor: reduce);
        prints.writeln("  '$name/$reduce': '${fingerprint(image)}',");
      } on J2kDecodeException {
        prints.writeln("  '$name/$reduce': 'error',");
      }
    }
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln('/// `fingerprint` of each fixture decoded at `name/reduction`,')
    ..writeln("/// or 'error' where that reduction doesn't exist.")
    ..writeln('const j2kFingerprints = <String, String>{')
    ..write(prints)
    ..writeln('};');
  File('test/jpeg2000/j2k_fixtures.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('Wrote ${files.length} fixtures.');
}
