import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/foundation.dart' show compute;
import 'package:image/image.dart' as img;

import '../errors.dart';
import '../svs/svs_file.dart';
import '../tiff/tiff_types.dart' show tilesAcross;
import '../tiff/tiff_writer.dart';
import 'image_adjustments.dart';
import 'image_export.dart' show defaultExportMaxPixels;
import 'region_decoder.dart';

/// Crops [level]'s (`x`,`y`)-`width`x`height` rectangle — see [readSvsRegion]
/// for coordinate semantics — and re-encodes it as a brand new, valid
/// multi-level pyramidal `.svs` file (a tiled BigTIFF with JPEG-compressed
/// tiles and an Aperio-style `ImageDescription`), rather than a single flat
/// raster image. The result can be reopened with [SvsFile.open] — by this
/// package or any other tiled-TIFF/OpenSlide-aware tool — and panned/zoomed
/// like any other slide.
///
/// [tileSize] is the tile edge length for every generated level (default
/// 256, matching real Aperio files). [quality] (1-100) is the JPEG quality
/// for every tile. Levels are generated by halving the previous level's
/// dimensions (box-filter downsampled) until one fits in a single tile —
/// the same shape a real Aperio pyramid takes. [adjustments] (default
/// [SvsImageAdjustments.none]) is applied once, to the source crop, before
/// the pyramid is built — every generated level reflects it.
///
/// [maxPixels] (default [defaultExportMaxPixels]) guards the *source* crop
/// size the same way [exportSvsLevel]'s `maxPixels` does — the whole crop is
/// decoded and pyramid-built in memory, so an accidentally huge rectangle
/// fails fast instead of stalling or OOM-ing the app.
///
/// Must run on the main isolate, like [readSvsRegion].
Future<Uint8List> exportSvsRegionAsSvs(
  SvsFile svsFile, {
  required int level,
  required int x,
  required int y,
  required int width,
  required int height,
  int tileSize = 256,
  int quality = 90,
  int maxPixels = defaultExportMaxPixels,
  SvsImageAdjustments adjustments = SvsImageAdjustments.none,
}) async {
  if (level < 0 || level >= svsFile.levels.length) {
    throw SvsFormatException(
      'Level $level out of range (have ${svsFile.levels.length} levels)',
    );
  }
  if (tileSize <= 0) {
    throw ArgumentError.value(tileSize, 'tileSize', 'must be positive');
  }
  final pixelCount = width * height;
  if (pixelCount > maxPixels) {
    final estimatedMb = (pixelCount * 4 / (1024 * 1024)).round();
    throw ArgumentError(
      'Requested region is ${width}x$height ($pixelCount px), over the '
      '$maxPixels px safety limit (~$estimatedMb MB just for the raw pixel '
      'buffer). Crop a smaller rectangle, or raise maxPixels if you really '
      'mean it.',
    );
  }

  final regionImage = await readSvsRegion(
    svsFile,
    level: level,
    x: x,
    y: y,
    width: width,
    height: height,
  );
  final Uint8List pixels;
  try {
    final data = await regionImage.toByteData(
      format: ui.ImageByteFormat.rawRgba,
    );
    if (data == null) {
      throw StateError(
        'Image.toByteData returned null (the image may already be disposed)',
      );
    }
    // A standalone copy, not a view over `data`'s buffer — `compute` sends
    // it to another isolate, which can't share memory with this one.
    pixels = Uint8List.fromList(
      data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
    );
  } finally {
    regionImage.dispose();
  }

  final sourceLevel = svsFile.levels[level];
  final sourceMppX = svsFile.metadata.mppX;
  final mpp = sourceMppX == null ? null : sourceMppX * sourceLevel.downsample;

  // Everything from here on (adjustments, downsampling, JPEG encoding, the
  // BigTIFF write) is pure computation on plain data — no `dart:ui`
  // involved — so it runs on a background isolate instead of blocking
  // whichever isolate called this (typically the main/UI isolate, since
  // `readSvsRegion` above requires it). A large crop can mean encoding well
  // over a thousand tiles across the whole pyramid; without this, that
  // freezes the UI for the entire duration.
  return compute(
    _buildPyramidBytes,
    _PyramidBuildParams(
      pixels: pixels,
      width: width,
      height: height,
      tileSize: tileSize,
      quality: quality,
      mpp: mpp,
      appMag: svsFile.metadata.appMag,
      brightness: adjustments.brightness,
      contrast: adjustments.contrast,
      shadows: adjustments.shadows,
      highlights: adjustments.highlights,
    ),
  );
}

/// Everything [exportSvsRegionAsSvs] does after decoding the source region —
/// packaged as a top-level function + a plain-data argument so [compute] can
/// run it on a background isolate.
class _PyramidBuildParams {
  final Uint8List pixels;
  final int width;
  final int height;
  final int tileSize;
  final int quality;
  final double? mpp;
  final int? appMag;
  final double brightness;
  final double contrast;
  final double shadows;
  final double highlights;

  const _PyramidBuildParams({
    required this.pixels,
    required this.width,
    required this.height,
    required this.tileSize,
    required this.quality,
    required this.mpp,
    required this.appMag,
    required this.brightness,
    required this.contrast,
    required this.shadows,
    required this.highlights,
  });
}

Uint8List _buildPyramidBytes(_PyramidBuildParams params) {
  final adjustments = SvsImageAdjustments(
    brightness: params.brightness,
    contrast: params.contrast,
    shadows: params.shadows,
    highlights: params.highlights,
  );
  adjustments.applyToRgba(params.pixels);

  var current = img.Image.fromBytes(
    width: params.width,
    height: params.height,
    bytes: params.pixels.buffer,
    bytesOffset: params.pixels.offsetInBytes,
    numChannels: 4,
    order: img.ChannelOrder.rgba,
  );

  final tileSize = params.tileSize;
  final writerLevels = <TiffWriterLevel>[];
  var levelIndex = 0;
  while (true) {
    final levelWidth = current.width;
    final levelHeight = current.height;
    final tilesX = tilesAcross(levelWidth, tileSize);
    final tilesY = tilesAcross(levelHeight, tileSize);

    final tileBytes = <Uint8List>[];
    for (var ty = 0; ty < tilesY; ty++) {
      for (var tx = 0; tx < tilesX; tx++) {
        final tileLeft = tx * tileSize;
        final tileTop = ty * tileSize;
        final tileW = math.min(tileSize, levelWidth - tileLeft);
        final tileH = math.min(tileSize, levelHeight - tileTop);
        final tile = img.copyCrop(
          current,
          x: tileLeft,
          y: tileTop,
          width: tileW,
          height: tileH,
        );
        tileBytes.add(img.encodeJpg(tile, quality: params.quality));
      }
    }

    writerLevels.add(
      TiffWriterLevel(
        width: levelWidth,
        height: levelHeight,
        tileWidth: tileSize,
        tileLength: tileSize,
        imageDescription: levelIndex == 0
            ? _buildImageDescription(
                width: levelWidth,
                height: levelHeight,
                tileSize: tileSize,
                quality: params.quality,
                mpp: params.mpp,
                appMag: params.appMag,
              )
            : null,
        tileJpegBytes: tileBytes,
      ),
    );

    if (levelWidth <= tileSize && levelHeight <= tileSize) break;
    final nextWidth = math.max(1, (levelWidth / 2).ceil());
    final nextHeight = math.max(1, (levelHeight / 2).ceil());
    current = img.copyResize(
      current,
      width: nextWidth,
      height: nextHeight,
      interpolation: img.Interpolation.average,
    );
    levelIndex++;
  }

  return writeTiledPyramidBigTiff(writerLevels);
}

/// Same as [exportSvsRegionAsSvs], but writes the encoded bytes straight to
/// [path] instead of returning them.
Future<File> exportSvsRegionAsSvsToFile(
  SvsFile svsFile, {
  required String path,
  required int level,
  required int x,
  required int y,
  required int width,
  required int height,
  int tileSize = 256,
  int quality = 90,
  int maxPixels = defaultExportMaxPixels,
  SvsImageAdjustments adjustments = SvsImageAdjustments.none,
}) async {
  final bytes = await exportSvsRegionAsSvs(
    svsFile,
    level: level,
    x: x,
    y: y,
    width: width,
    height: height,
    tileSize: tileSize,
    quality: quality,
    maxPixels: maxPixels,
    adjustments: adjustments,
  );
  return File(path).writeAsBytes(bytes);
}

/// An Aperio-style `ImageDescription` for the cropped file's level 0 —
/// enough for [SvsMetadata.parse] (via [SvsFile.open]) to recover [mpp] and
/// [appMag] when the exported file is reopened.
String _buildImageDescription({
  required int width,
  required int height,
  required int tileSize,
  required int quality,
  required double? mpp,
  required int? appMag,
}) {
  final header =
      'Aperio Image Library v1.0\r\n'
      '${width}x$height [0,0 ${width}x$height] ($tileSize x $tileSize) '
      'JPEG/RGB Q=$quality';
  final fields = <String>[
    if (appMag != null) 'AppMag = $appMag',
    if (mpp != null) 'MPP = ${mpp.toStringAsFixed(4)}',
  ];
  return fields.isEmpty ? header : '$header|${fields.join('|')}';
}
