import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:image/image.dart' as img;
import 'package:openjpeg_ffi/openjpeg_ffi.dart';

import '../errors.dart';
import '../svs/aperio_tags.dart';
import '../svs/svs_file.dart';
import '../tiff/tiff_types.dart';
import '../tiff/tiff_writer.dart';
import 'image_adjustments.dart';
import 'region_decoder.dart';

/// Tile compression for [exportSvsRegionAsSvs]/[exportSvsRegionAsSvsToFile]
/// to (re-)encode the crop's pyramid with — the same two schemes
/// [SvsLevel]/[SvsFile] can already read back (`svs/svs_file.dart`).
enum SvsExportCompression {
  /// New-style JPEG (TIFF `Compression` 7) — lossy, controlled by that
  /// function's `quality` parameter. The default: fast, universally
  /// supported, matches what most real Aperio slides already use.
  jpeg,

  /// JPEG2000 (TIFF `Compression` 33005), via `openjpeg_ffi`'s `encodeJ2k` —
  /// mathematically lossless by default, or lossy at a chosen ratio via
  /// that function's `jp2kCompressionRatio` parameter; typically a
  /// meaningfully smaller file than JPEG at comparable visual quality,
  /// at the cost of slower encoding. Matches what real Aperio JP2K slides
  /// use.
  jpeg2000,
}

/// Crops [level]'s (`x`,`y`)-`width`x`height` rectangle — see [readSvsRegion]
/// for coordinate semantics — and re-encodes it as a brand new, valid
/// multi-level pyramidal `.svs` file (a tiled BigTIFF with JPEG-compressed
/// tiles and an Aperio-style `ImageDescription`), rather than a single flat
/// raster image. The result can be reopened with [SvsFile.open] — by this
/// package or any other tiled-TIFF/OpenSlide-aware tool — and panned/zoomed
/// like any other slide.
///
/// [tileSize] is the tile edge length for every generated level (default
/// 256, matching real Aperio files — or, if [matchSourceCompression] is
/// `true` and [tileSize] is left `null`, [level]'s own tile edge length
/// instead). Levels are generated by halving the
/// previous level's dimensions (box-filter downsampled) until one fits in a
/// single tile — the same shape a real Aperio pyramid takes. [adjustments]
/// (default [SvsImageAdjustments.none]) is applied once, to the source
/// crop, before the pyramid is built — every generated level reflects it.
///
/// [compression] (default [SvsExportCompression.jpeg]) picks the pyramid's
/// tile encoding. [quality] (1-100) is the JPEG quality for every tile —
/// only meaningful when `compression` is [SvsExportCompression.jpeg].
/// [jp2kCompressionRatio] (default 0 = mathematically lossless) is the
/// JPEG2000 target size-reduction ratio (e.g. 20 means roughly 20:1
/// smaller than uncompressed) — only meaningful when `compression` is
/// [SvsExportCompression.jpeg2000]; see `openjpeg_ffi`'s `encodeJ2k` for
/// the exact semantics.
///
/// [matchSourceCompression] (default `false`), when `true`, ignores
/// `compression`/`quality`/`jp2kCompressionRatio` above and instead derives
/// them from [level] itself: the same compression scheme the source already
/// uses (JPEG stays JPEG, JPEG2000 stays JPEG2000), plus either the same
/// JPEG quality (parsed from the source's own `ImageDescription`, e.g.
/// `Q=90`) or an equivalent JPEG2000 ratio (estimated by sampling a handful
/// of the source's actual on-disk tile sizes at that level, since Aperio
/// doesn't record the ratio a JP2K file was encoded at). This is the "keep
/// the crop as close to the source as this format allows" mode — useful
/// because a small crop re-encoded at this function's own defaults (quality
/// 90, or lossless JP2K) can easily end up *larger* than the corresponding
/// region of the source file if the source was actually encoded leaner
/// (e.g. `Q=70`, or a lossy JP2K ratio). Falls back to `quality`/
/// `jp2kCompressionRatio` above when the source's own quality/ratio can't be
/// determined (e.g. no `Q=` in its `ImageDescription`, or every sampled tile
/// is sparse). It also changes [tileSize]'s default: a `null` [tileSize]
/// resolves to [level]'s own tile edge length instead of 256, so a crop
/// whose source uses a non-256 tile grid (e.g. 240) still ends up with the
/// same tile size rather than an arbitrary one — pass [tileSize] explicitly
/// to override this too.
///
/// The exported file always gets a thumbnail (needed for `SvsImageView`'s
/// minimap) generated from the crop itself, but two other pieces of the
/// source file are opt-in/opt-out, since a crop is often shared outside the
/// context that made them meaningful: [includeLabelAndMacroImages] (default
/// `true`) copies the source file's own label/macro associated images
/// across unmodified — they describe the whole physical slide, not just the
/// cropped region, so a caller cropping out a small region to share might
/// not want the slide's label riding along; pass `false` to omit them (and
/// shrink the output). [includeSourceMetadata] (default `true`) carries
/// every other `ImageDescription` field the source file had (Filename,
/// Date, Time, User, ScanScope ID, etc. — anything beyond the `AppMag`/`MPP`
/// this function always recomputes for the crop) into the exported file's
/// own `ImageDescription`; pass `false` for just `AppMag`/`MPP`, e.g. to
/// avoid carrying the original filename/scanner details into a
/// redistributed crop.
///
/// Built by streaming the source region band-by-band (bounded memory —
/// roughly `tileSize * width * 4` bytes regardless of how tall the crop is,
/// not `width * height * 4`), so there's no pixel-count safety limit by
/// default. [maxPixels], if given, still throws [ArgumentError] up front for
/// a crop over that size — useful if a caller wants to keep the old
/// fail-fast behavior for a specific size budget. [onProgress] (0.0-1.0), if
/// given, is invoked as each band of the source is processed.
///
/// This returns the whole encoded file as bytes, which — unlike building the
/// file itself — *does* need that many bytes of RAM to hold the return
/// value. For a crop large enough that this matters, prefer
/// [exportSvsRegionAsSvsToFile], which streams straight to disk instead.
///
/// Must run on the main isolate, like [readSvsRegion].
Future<Uint8List> exportSvsRegionAsSvs(
  SvsFile svsFile, {
  required int level,
  required int x,
  required int y,
  required int width,
  required int height,
  int? tileSize,
  int quality = 90,
  SvsExportCompression compression = SvsExportCompression.jpeg,
  double jp2kCompressionRatio = 0,
  bool matchSourceCompression = false,
  int? maxPixels,
  SvsImageAdjustments adjustments = SvsImageAdjustments.none,
  bool includeLabelAndMacroImages = true,
  bool includeSourceMetadata = true,
  void Function(double progress)? onProgress,
}) async {
  final tempDir = await Directory.systemTemp.createTemp('svs_region_export_');
  final tempFile = File('${tempDir.path}/region.svs');
  try {
    await _streamSvsRegionAsSvs(
      svsFile,
      outFile: tempFile,
      level: level,
      x: x,
      y: y,
      width: width,
      height: height,
      tileSize: tileSize,
      quality: quality,
      compression: compression,
      jp2kCompressionRatio: jp2kCompressionRatio,
      matchSourceCompression: matchSourceCompression,
      maxPixels: maxPixels,
      adjustments: adjustments,
      includeLabelAndMacroImages: includeLabelAndMacroImages,
      includeSourceMetadata: includeSourceMetadata,
      onProgress: onProgress,
    );
    return await tempFile.readAsBytes();
  } finally {
    await tempDir.delete(recursive: true);
  }
}

/// Same as [exportSvsRegionAsSvs], but streams the encoded file straight to
/// [path] instead of returning it — the memory-bounded way to export a
/// crop that's too large to comfortably hold as a single in-memory
/// [Uint8List].
Future<File> exportSvsRegionAsSvsToFile(
  SvsFile svsFile, {
  required String path,
  required int level,
  required int x,
  required int y,
  required int width,
  required int height,
  int? tileSize,
  int quality = 90,
  SvsExportCompression compression = SvsExportCompression.jpeg,
  double jp2kCompressionRatio = 0,
  bool matchSourceCompression = false,
  int? maxPixels,
  SvsImageAdjustments adjustments = SvsImageAdjustments.none,
  bool includeLabelAndMacroImages = true,
  bool includeSourceMetadata = true,
  void Function(double progress)? onProgress,
}) async {
  final file = File(path);
  await _streamSvsRegionAsSvs(
    svsFile,
    outFile: file,
    level: level,
    x: x,
    y: y,
    width: width,
    height: height,
    tileSize: tileSize,
    quality: quality,
    compression: compression,
    jp2kCompressionRatio: jp2kCompressionRatio,
    matchSourceCompression: matchSourceCompression,
    maxPixels: maxPixels,
    adjustments: adjustments,
    includeLabelAndMacroImages: includeLabelAndMacroImages,
    includeSourceMetadata: includeSourceMetadata,
    onProgress: onProgress,
  );
  return file;
}

Future<void> _streamSvsRegionAsSvs(
  SvsFile svsFile, {
  required File outFile,
  required int level,
  required int x,
  required int y,
  required int width,
  required int height,
  required int? tileSize,
  required int quality,
  required SvsExportCompression compression,
  required double jp2kCompressionRatio,
  required bool matchSourceCompression,
  required int? maxPixels,
  required SvsImageAdjustments adjustments,
  required bool includeLabelAndMacroImages,
  required bool includeSourceMetadata,
  required void Function(double progress)? onProgress,
}) async {
  if (level < 0 || level >= svsFile.levels.length) {
    throw SvsFormatException(
      'Level $level out of range (have ${svsFile.levels.length} levels)',
    );
  }
  if (width <= 0 || height <= 0) {
    throw ArgumentError('width/height must be positive, got ${width}x$height');
  }
  final pixelCount = width * height;
  if (maxPixels != null && pixelCount > maxPixels) {
    final estimatedMb = (pixelCount * 4 / (1024 * 1024)).round();
    throw ArgumentError(
      'Requested region is ${width}x$height ($pixelCount px), over the '
      '$maxPixels px safety limit (~$estimatedMb MB just for the raw pixel '
      'buffer). Crop a smaller rectangle, or pass a higher maxPixels if you '
      'really mean it.',
    );
  }

  final sourceLevel = svsFile.levels[level];
  // `null` means "auto": this function's own usual default (256), unless
  // matchSourceCompression is also matching the source's own tile grid.
  final effectiveTileSize =
      tileSize ?? (matchSourceCompression ? sourceLevel.tileWidth : 256);
  if (effectiveTileSize <= 0) {
    throw ArgumentError.value(tileSize, 'tileSize', 'must be positive');
  }
  final sourceMppX = svsFile.metadata.mppX;
  final mpp = sourceMppX == null ? null : sourceMppX * sourceLevel.downsample;
  final appMag = svsFile.metadata.appMag;

  if (matchSourceCompression) {
    if (sourceLevel.isJp2k) {
      compression = SvsExportCompression.jpeg2000;
      jp2kCompressionRatio =
          await _estimateSourceJp2kRatio(sourceLevel) ?? jp2kCompressionRatio;
    } else {
      compression = SvsExportCompression.jpeg;
      quality = await _parseSourceJpegQuality(sourceLevel) ?? quality;
    }
  }

  // The source file's own label/macro associated images don't change with
  // the crop — they describe the whole physical slide — so, unless the
  // caller opted out via `includeLabelAndMacroImages`, they're carried into
  // the exported file unmodified (raw strip bytes copied as-is, no decode/
  // re-encode) rather than dropped, same as a real Aperio file would have
  // them.
  final labelAndMacroImages = includeLabelAndMacroImages
      ? svsFile.associatedImages
            .where(
              (a) =>
                  a.kind == AssociatedImageKind.label ||
                  a.kind == AssociatedImageKind.macro,
            )
            .toList(growable: false)
      : const <SvsAssociatedImage>[];

  final tileCompression = compression == SvsExportCompression.jpeg2000
      ? ApCompression.jp2k
      : ApCompression.newJpeg;

  final levelDims = computePyramidLevelDims(width, height, effectiveTileSize);
  final specs = [
    for (var i = 0; i < levelDims.length; i++)
      PyramidLevelSpec(
        width: levelDims[i].$1,
        height: levelDims[i].$2,
        tileWidth: effectiveTileSize,
        tileLength: effectiveTileSize,
        compression: tileCompression,
        imageDescription: i == 0
            ? _buildImageDescription(
                width: levelDims[0].$1,
                height: levelDims[0].$2,
                tileSize: effectiveTileSize,
                quality: quality,
                compression: compression,
                mpp: mpp,
                appMag: appMag,
                sourceFields: includeSourceMetadata
                    ? svsFile.metadata.raw
                    : const {},
              )
            : null,
      ),
  ];
  // The coarsest generated level (last in `specs`, already <= tileSize in
  // both dimensions) doubles as the exported file's thumbnail — an
  // associated image `SvsImageView`'s minimap needs, same as a real Aperio
  // file carries, which a plain pyramid-levels-only export previously never
  // wrote at all.
  final thumbSpec = AssociatedImageSpec(
    width: levelDims.last.$1,
    height: levelDims.last.$2,
    compression: ApCompression.newJpeg,
    photometricInterpretation: 6, // YCbCr — img.encodeJpg's normal output
    samplesPerPixel: 3,
    bitsPerSample: const [8, 8, 8],
    predictor: 1,
    rowsPerStrip: levelDims.last.$2,
    stripCount: 1,
  );
  final extraSpecs = [
    for (final image in labelAndMacroImages) await _copySpec(image),
  ];
  final layout = planPyramidHeader(
    specs,
    associatedImages: [thumbSpec, ...extraSpecs],
  );

  if (await outFile.exists()) await outFile.delete();
  final raf = await outFile.open(mode: FileMode.write);
  try {
    await raf.writeFrom(layout.headerBytes);

    final sink = _TileSink(raf, specs.length);
    final builders = [
      for (var i = 0; i < specs.length; i++)
        _LevelBuilder(
          levelIndex: i,
          spec: specs[i],
          quality: quality,
          jp2kCompressionRatio: jp2kCompressionRatio,
          sink: sink,
        ),
    ];
    for (var i = 0; i < builders.length - 1; i++) {
      builders[i].next = builders[i + 1];
    }

    var rowsProcessed = 0;
    var srcY = 0;
    while (srcY < height) {
      final bandHeight = math.min(effectiveTileSize, height - srcY);
      final raw = await readSvsRegionRawRgba(
        svsFile,
        level: level,
        x: x,
        y: y + srcY,
        width: width,
        height: bandHeight,
      );
      adjustments.applyToRgba(raw);
      await builders[0].addRows([
        for (var r = 0; r < bandHeight; r++)
          Uint8List.sublistView(raw, r * width * 4, (r + 1) * width * 4),
      ]);

      rowsProcessed += bandHeight;
      srcY += bandHeight;
      onProgress?.call(rowsProcessed / height);
      // Yield between bands so the UI (this all runs on the main isolate —
      // tile decoding needs `dart:ui`) can still service a frame.
      await Future(() {});
    }
    await builders[0].finish();
    // Captured after every level (including the coarsest, which never has a
    // `next`) has finished — `_LevelBuilder._emitBand` only ever runs once
    // for the coarsest level, covering its whole (already <= tileSize)
    // extent in one band, so this is the complete thumbnail image.
    final thumbnailImage = builders.last.finalImage!;
    var writePos = await raf.position();

    final thumbBytes = img.encodeJpg(thumbnailImage, quality: quality);
    final thumbOffset = writePos;
    await raf.setPosition(writePos);
    await raf.writeFrom(thumbBytes);
    writePos += thumbBytes.length;
    if (writePos.isOdd) {
      await raf.writeFrom(Uint8List(1));
      writePos += 1;
    }

    // Each label/macro image's strips are copied byte-for-byte (no decode,
    // no re-encode) straight from the source file.
    final extraStripData = <(List<int>, List<int>)>[];
    for (final source in labelAndMacroImages) {
      final stripCount = await source.stripCount;
      final offsets = <int>[];
      final byteCounts = <int>[];
      for (var i = 0; i < stripCount; i++) {
        final bytes = await source.readRawStripBytes(i);
        if (bytes.isEmpty) {
          offsets.add(0);
          byteCounts.add(0);
          continue;
        }
        offsets.add(writePos);
        byteCounts.add(bytes.length);
        await raf.setPosition(writePos);
        await raf.writeFrom(bytes);
        writePos += bytes.length;
        if (writePos.isOdd) {
          await raf.writeFrom(Uint8List(1));
          writePos += 1;
        }
      }
      extraStripData.add((offsets, byteCounts));
    }

    for (var i = 0; i < specs.length; i++) {
      final patch = layout.levels[i];
      await raf.setPosition(patch.tileOffsetsValuePos);
      await raf.writeFrom(
        encodeTiffInts(sink.offsetsPerLevel[i], TiffType.long8),
      );
      await raf.setPosition(patch.tileByteCountsValuePos);
      await raf.writeFrom(
        encodeTiffInts(sink.byteCountsPerLevel[i], TiffType.long),
      );
    }

    final thumbPatch = layout.associatedImages[0];
    await raf.setPosition(thumbPatch.stripOffsetsValuePos);
    await raf.writeFrom(encodeTiffInts([thumbOffset], TiffType.long8));
    await raf.setPosition(thumbPatch.stripByteCountsValuePos);
    await raf.writeFrom(encodeTiffInts([thumbBytes.length], TiffType.long));

    for (var i = 0; i < labelAndMacroImages.length; i++) {
      final patch = layout.associatedImages[1 + i];
      final (offsets, byteCounts) = extraStripData[i];
      await raf.setPosition(patch.stripOffsetsValuePos);
      await raf.writeFrom(encodeTiffInts(offsets, TiffType.long8));
      await raf.setPosition(patch.stripByteCountsValuePos);
      await raf.writeFrom(encodeTiffInts(byteCounts, TiffType.long));
    }
  } finally {
    await raf.close();
  }
}

/// The JPEG quality [sourceLevel] was itself encoded at, parsed straight out
/// of its own `ImageDescription` (e.g. `...(256x256) JPEG/RGB Q=70...`) —
/// or `null` if that level has no `ImageDescription`, or it has no `Q=NN`
/// in it. Used by [matchSourceCompression] instead of guessing.
final _jpegQualityPattern = RegExp(r'Q\s*=\s*(\d+)');

Future<int?> _parseSourceJpegQuality(SvsLevel sourceLevel) async {
  final description = await sourceLevel.imageDescription;
  if (description == null) return null;
  final match = _jpegQualityPattern.firstMatch(description);
  if (match == null) return null;
  return int.tryParse(match.group(1)!);
}

/// An effective JPEG2000 `compressionRatio` (see `encodeJ2k`) that
/// approximates how hard [sourceLevel] was itself actually compressed —
/// unlike JPEG quality, Aperio never records this in `ImageDescription`, so
/// it's estimated by sampling a handful of the level's real on-disk tile
/// byte counts and comparing them against that tile's uncompressed
/// (width x height x 3-channel RGB) size. Returns `null` if every sampled
/// tile turns out to be sparse (byte count 0), leaving nothing to measure.
Future<double?> _estimateSourceJp2kRatio(SvsLevel sourceLevel) async {
  final tilesX = sourceLevel.tilesAcrossX;
  final tilesY = sourceLevel.tilesAcrossY;
  final totalTiles = tilesX * tilesY;
  if (totalTiles == 0) return null;

  const maxSamples = 8;
  final sampleCount = math.min(maxSamples, totalTiles);
  var sampledBytes = 0;
  var sampledTiles = 0;
  for (var i = 0; i < sampleCount; i++) {
    final tileIndex = (i * totalTiles) ~/ sampleCount;
    final tx = tileIndex % tilesX;
    final ty = tileIndex ~/ tilesX;
    final byteCount = await sourceLevel.tileByteCount(tx, ty);
    if (byteCount <= 0) continue;
    sampledBytes += byteCount;
    sampledTiles++;
  }
  if (sampledTiles == 0) return null;

  final uncompressedTileBytes =
      sourceLevel.tileWidth * sourceLevel.tileLength * 3;
  final avgBytes = sampledBytes / sampledTiles;
  // Clamped to encodeJ2k's practically useful range — an unclamped ratio
  // from a near-empty or degenerate tile could otherwise come out absurdly
  // high (or below 1, i.e. "expand").
  return (uncompressedTileBytes / avgBytes).clamp(1.0, 500.0);
}

/// Builds an [AssociatedImageSpec] that lets [image]'s strips be copied
/// byte-for-byte into the exported file — same compression/photometric/
/// sample layout/JPEGTables/description as the source, so the copy decodes
/// identically once reopened.
Future<AssociatedImageSpec> _copySpec(SvsAssociatedImage image) async {
  return AssociatedImageSpec(
    width: image.width,
    height: image.height,
    compression: image.compression,
    photometricInterpretation: image.photometricInterpretation,
    samplesPerPixel: image.samplesPerPixel,
    bitsPerSample: image.bitsPerSample,
    predictor: image.predictor,
    rowsPerStrip: await image.rowsPerStrip,
    stripCount: await image.stripCount,
    jpegTables: image.isJpeg ? await image.jpegTables : null,
    imageDescription: await image.imageDescription,
  );
}

/// Sequentially appends tile JPEG bytes to the output file (starting right
/// after the header `planPyramidHeader` already wrote), recording each
/// tile's final file offset/byte-count for the header patch pass. Tiles for
/// a level must be written in row-major (`ty * tilesAcrossX + tx`) order —
/// `_LevelBuilder` always emits full tile-row bands in that order, so this
/// never needs to reorder anything.
class _TileSink {
  final RandomAccessFile raf;
  final List<List<int>> offsetsPerLevel;
  final List<List<int>> byteCountsPerLevel;
  int _pos = -1;

  _TileSink(this.raf, int levelCount)
    : offsetsPerLevel = List.generate(levelCount, (_) => <int>[]),
      byteCountsPerLevel = List.generate(levelCount, (_) => <int>[]);

  Future<void> writeTile(int levelIndex, Uint8List bytes) async {
    _pos = _pos < 0 ? await raf.position() : _pos;
    offsetsPerLevel[levelIndex].add(_pos);
    byteCountsPerLevel[levelIndex].add(bytes.length);
    await raf.writeFrom(bytes);
    _pos += bytes.length;
    if (_pos.isOdd) {
      await raf.writeFrom(Uint8List(1));
      _pos += 1;
    }
  }
}

/// Builds one pyramid level by accumulating raw RGBA rows pushed in via
/// [addRows], flushing a JPEG-encoded, file-written tile-row band as soon as
/// [PyramidLevelSpec.tileLength] rows have accumulated (or, in [finish], the
/// final shorter band once the source is exhausted). Each flushed band is
/// also box-filter-downsampled 2x and pushed into [next] — the next-coarser
/// level's own accumulator — cascading the whole pyramid from a single
/// stream of level-0 source bands, never holding more than a couple of
/// tile-row bands per level in memory at once.
class _LevelBuilder {
  final int levelIndex;
  final PyramidLevelSpec spec;
  final int quality;
  final double jp2kCompressionRatio;
  final _TileSink sink;
  _LevelBuilder? next;

  /// Set only on the coarsest level (the one with no [next] to cascade
  /// into) — that level's single [_emitBand] call covers its whole extent
  /// (already `<= tileSize` in both dimensions by construction), so this
  /// ends up being the complete coarsest-level image once [finish] returns.
  /// The exported file's thumbnail reuses it rather than decoding/
  /// downsampling the source a second time.
  img.Image? finalImage;

  final List<Uint8List> _pendingRows = [];

  _LevelBuilder({
    required this.levelIndex,
    required this.spec,
    required this.quality,
    required this.jp2kCompressionRatio,
    required this.sink,
  });

  Future<void> addRows(List<Uint8List> rows) async {
    _pendingRows.addAll(rows);
    await _flushFullBands();
  }

  Future<void> finish() async {
    await _flushFullBands();
    if (_pendingRows.isNotEmpty) {
      final band = List<Uint8List>.of(_pendingRows);
      _pendingRows.clear();
      await _emitBand(band);
    }
    await next?.finish();
  }

  Future<void> _flushFullBands() async {
    while (_pendingRows.length >= spec.tileLength) {
      final band = _pendingRows.sublist(0, spec.tileLength);
      _pendingRows.removeRange(0, spec.tileLength);
      await _emitBand(band);
    }
  }

  Future<void> _emitBand(List<Uint8List> bandRows) async {
    final bandHeight = bandRows.length;
    final bandBytes = Uint8List(spec.width * bandHeight * 4);
    for (var r = 0; r < bandHeight; r++) {
      bandBytes.setRange(
        r * spec.width * 4,
        (r + 1) * spec.width * 4,
        bandRows[r],
      );
    }

    final bandImage = img.Image.fromBytes(
      width: spec.width,
      height: bandHeight,
      bytes: bandBytes.buffer,
      numChannels: 4,
      order: img.ChannelOrder.rgba,
    );
    if (next == null) finalImage = bandImage;
    for (var tx = 0; tx < spec.tilesAcrossX; tx++) {
      final tileLeft = tx * spec.tileWidth;
      final tileW = math.min(spec.tileWidth, spec.width - tileLeft);
      final tile = img.copyCrop(
        bandImage,
        x: tileLeft,
        y: 0,
        width: tileW,
        height: bandHeight,
      );
      final Uint8List tileBytes;
      if (spec.compression == ApCompression.jp2k) {
        // Unlike this builder's JPEG tiles — whose readers (`region_decoder
        // .dart`, `lod_controller.dart`) already handle a boundary tile
        // decoding smaller than nominal — every JP2K reader in this package
        // assumes a tile decodes at exactly the nominal tile-grid size
        // (true of real Aperio JP2K files, which always pad). So a boundary
        // tile here is padded up to that same full nominal size before
        // encoding, rather than encoded at its true (smaller) size like the
        // JPEG path above.
        final padded = tileW == spec.tileWidth && bandHeight == spec.tileLength
            ? tile
            : img.copyExpandCanvas(
                tile,
                newWidth: spec.tileWidth,
                newHeight: spec.tileLength,
                position: img.ExpandCanvasPosition.topLeft,
                backgroundColor: img.ColorRgb8(0, 0, 0),
              );
        tileBytes = encodeJ2k(
          padded.getBytes(order: img.ChannelOrder.rgb),
          width: spec.tileWidth,
          height: spec.tileLength,
          numComponents: 3,
          compressionRatio: jp2kCompressionRatio,
        );
      } else {
        tileBytes = img.encodeJpg(tile, quality: quality);
      }
      await sink.writeTile(levelIndex, tileBytes);
    }

    if (next != null) {
      await next!.addRows(_boxDownsample2x(bandBytes, spec.width, bandHeight));
    }
  }
}

/// Box-filters [src] (tightly-packed RGBA, [width]x[height]) down by 2x in
/// both dimensions, returning the result as a list of rows (row-major, each
/// `ceil(width / 2) * 4` bytes) rather than a flat buffer — matches
/// [_LevelBuilder.addRows]'s input shape directly. A trailing odd row/column
/// is averaged from just its single remaining source pixel(s), the same
/// "round up" rule [computePyramidLevelDims] uses to size the next level.
List<Uint8List> _boxDownsample2x(Uint8List src, int width, int height) {
  final outWidth = (width / 2).ceil();
  final outHeight = (height / 2).ceil();
  final rows = <Uint8List>[];
  for (var oy = 0; oy < outHeight; oy++) {
    final y0 = oy * 2;
    final hasY1 = y0 + 1 < height;
    final row = Uint8List(outWidth * 4);
    for (var ox = 0; ox < outWidth; ox++) {
      final x0 = ox * 2;
      final hasX1 = x0 + 1 < width;
      var r = 0, g = 0, b = 0, a = 0, count = 0;
      void accum(int xx, int yy) {
        final idx = (yy * width + xx) * 4;
        r += src[idx];
        g += src[idx + 1];
        b += src[idx + 2];
        a += src[idx + 3];
        count++;
      }

      accum(x0, y0);
      if (hasX1) accum(x0 + 1, y0);
      if (hasY1) accum(x0, y0 + 1);
      if (hasX1 && hasY1) accum(x0 + 1, y0 + 1);

      row[ox * 4] = (r / count).round();
      row[ox * 4 + 1] = (g / count).round();
      row[ox * 4 + 2] = (b / count).round();
      row[ox * 4 + 3] = (a / count).round();
    }
    rows.add(row);
  }
  return rows;
}

/// Fields from the source file's own `ImageDescription` that describe its
/// absolute position/size within the *original* slide — meaningless (and
/// actively misleading) once carried into a crop, so [_buildImageDescription]
/// drops them rather than copying them through with `sourceFields`.
const _positionalMetadataFields = {
  'Left',
  'Top',
  'OriginalWidth',
  'OriginalHeight',
};

/// An Aperio-style `ImageDescription` for the cropped file's level 0 —
/// enough for [SvsMetadata.parse] (via [SvsFile.open]) to recover [mpp] and
/// [appMag] when the exported file is reopened.
String _buildImageDescription({
  required int width,
  required int height,
  required int tileSize,
  required int quality,
  required SvsExportCompression compression,
  required double? mpp,
  required int? appMag,
  required Map<String, String> sourceFields,
}) {
  // Purely informational — `SvsMetadata.parse` only reads the `|`-separated
  // fields below, never this header line — so it's fine that "Q=" has no
  // real JPEG2000 equivalent.
  final encodingLabel = compression == SvsExportCompression.jpeg2000
      ? 'JP2000/RGB'
      : 'JPEG/RGB Q=$quality';
  final header =
      'Aperio Image Library v1.0\r\n'
      '${width}x$height [0,0 ${width}x$height] ($tileSize x $tileSize) '
      '$encodingLabel';
  final fields = <String>[
    if (appMag != null) 'AppMag = $appMag',
    if (mpp != null) 'MPP = ${mpp.toStringAsFixed(4)}',
    for (final entry in sourceFields.entries)
      // AppMag/MPP are recomputed above (MPP scales with the source level's
      // downsample, so the raw source value would be wrong here); every
      // other field the source file carried — Filename, Date, Time, User,
      // ScanScope ID, StripeWidth, DisplayColor, etc. — is preserved as-is.
      if (entry.key != 'AppMag' &&
          entry.key != 'MPP' &&
          !_positionalMetadataFields.contains(entry.key))
        '${entry.key} = ${entry.value}',
  ];
  return fields.isEmpty ? header : '$header|${fields.join('|')}';
}
